### ISSUE TITLE
Xcode 11.4 / Swift 5.2 Support

### ISSUE THREAD

**Issue by jimmya** [mopinion/mopinion-sdk-ios-web#10]
The framework needs to be updated for the new Xcode and Swift updates.

I'm using the framework through Carthage. This means my project won't compile when using a framework built with swift 5.1.3.

**Comment by GustaafL** [comment]
Thank you for your question. We expect to be able to release the new version using the latest versions of Xcode and Swift in the coming 2 weeks. We will notify you when the new version is available.

**Comment by davidvpe** [comment]
@GustaafL it's been already 2 weeks, any updates on this?

**Comment by dandreikiv** [comment]
@GustaafL do you have any update on when new version will be available?

**Comment by GustaafL** [comment]
Hi,
Sadly there will be a slight delay. We expect to release the new version of the SDK on Tuesday at the latest.

**Comment by siddarthgandhi** [comment]
Could you please update the cocoapods repo with the latest version so we could use it?

**Comment by stevenkuipers** [comment]
Hi All,
The latest version of the SDK has been updated for Xcode 11.4 and Swift 5.2.

@siddarthgandhi, Cocoapods version has been updated as well.
