### ISSUE TITLE
Proper M1 support

### ISSUE THREAD

**Issue by jimmya** [mopinion/mopinion-sdk-ios-web#12]
Hi,

Could you please release a version of this SDK as a XCFramework? We don't use cocoapods but host this framework internally so we can use SPM.

Best regards,

Jimmy

**Comment by mopinion-support** [comment]
Hi Jimmy,

Thanks for your request. We will discuss whether this is possible. We will update you accordingly.

Kind regards,

Pieter

**Comment by Piethot** [comment]
Hi Jimmy,

We will be releasing this SDK as a XCFramework in the near future. I will let you know when it has been released.

Kind regards,

Pieter

**Comment by jimmya** [comment]
@Piethot any update on this?

**Comment by mbernson** [comment]
Hi,

Our team would like to move away from Cocoapods entirely and Mopinion is one of the last hold-outs. 🙂

Check out the [WWDC2020 talk: Distribute binary frameworks as Swift packages](https://developer.apple.com/videos/play/wwdc2020/10147/) and the [Apple docs](https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages)

**Comment by mohwaili** [comment]
Any updates?

**Comment by cristan** [comment]
I've tested it and Apple Silicon works now on version 0.5.0 whose release notes are on [full display](https://github.com/mopinion/mopinion-sdk-ios-web#release-notes-for-version-050) at the project page. This issue can therefore be closed.

**Comment by MattAydin** [comment]
Thank you very much for the update @cristan 👍🏻
