### ISSUE TITLE
Missing an expected key: 'NSPrivacyCollectedDataTypes'

### ISSUE THREAD

**Issue by Gois** [mopinion/mopinion-sdk-ios-web#13]
When you generate a privacy report in Xcode, it will show an error:
`Missing an expected key: 'NSPrivacyCollectedDataTypes'`

The version I'm using is: 0.7.1-swiftpm

**Comment by Piethot** [comment]
Hi @Gois, thanks for reporting this issue. We have determined the cause and have this fixed in an upcoming release. As soon as the release is available we will let you know.

**Comment by Piethot** [comment]
Hi @Gois the release that fixes this issue is now available. https://github.com/mopinion/mopinion-sdk-ios-web/releases/tag/0.7.2-swiftpm. Please let us know if you still encounter any issue by reopening this issue.
