### ISSUE TITLE
Mopinion does not dismiss automatically

### ISSUE THREAD

**Issue by MichaelNL** [mopinion/mopinion-sdk-ios-web#2]
When we start mopinion with the following code: 
`MopinionSDK.load("<KEY>", true)`
and
`MopinionSDK.event(self, "<EVENT>")`

Then after filling in the survey, the newly presented view controller of mopinion does not dismiss automatically. Instead the user sees a rotating checkmark and then afterwards a white screen with option to close manually.

Is there a way to have this close automatically?

**Comment by welstarco** [comment]
Thank you for your feedback. We're actively adding features to our SDKs and indeed automatically closing the feedback form as possible in our webforms is not yet implemented in our SDK. We're planning to implement this feature in a future release.

**Comment by MichaelNL** [comment]
Do you have any indication on when this will be added?

**Comment by stevenkuipers** [comment]
Hi Michael,

This is something we will cover in the next version update. Unfortunately, we cannot give you an ETA on the release date. We will close this issue for now and will let you know when it is implemented. 
If you have questions you can also contact us at support@mopinion.com
