### ISSUE TITLE
swift 5.1 support

### ISSUE THREAD

**Issue by minhpo** [mopinion/mopinion-sdk-ios-web#6]
Will you support Swift 5.1? And when will this be released?

**Comment by GustaafL** [comment]
Thank you for your question. As of yet Swift 5.1 has not been officially released. When this is released we will start working on a release that supports Swift 5.1.

Can you please leave us a message at support@mopinion.com? We would like to know for which customer you are asking this.

**Comment by GustaafL** [comment]
A new beta version of our SDK has been released. SDK mopinion-sdk-ios-web version 0.4.0 is now available and supports Swift 5.1 and Xcode 11 beta. It will have the same functionalities as the mopinion-sdk-ios-web version 0.3.4 SDK.
